"use client";

import { FormEvent, useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Textarea } from "@/components/ui/textarea";
import { ToastProvider, useToast } from "@/components/ui/toast";
import { ChatThread } from "@/components/examination/chat-thread";
import { Bdi } from "@/components/shared/bdi";
import { sendMessage, markMessagesRead, broadcastOwnerMessage } from "@/lib/messaging/actions";
import type { Message, Profile } from "@/types/database";

interface MessagesClientProps { currentUserId: string; profiles: Profile[]; messages: Message[]; roleLabel: string; }

function MessagesInner({ currentUserId, profiles, messages, roleLabel }: MessagesClientProps) {
  const router = useRouter(); const { toast } = useToast();
  const [selectedUserId, setSelectedUserId] = useState<string | null>(null); const [search, setSearch] = useState("");
  const [body, setBody] = useState(""); const [broadcastBody, setBroadcastBody] = useState("");
  const [broadcastOpen, setBroadcastOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [broadcasting, setBroadcasting] = useState(false);
  const [, startReadTransition] = useTransition();
  const recipients = useMemo(() => profiles.filter((p) => p.user_id !== currentUserId && p.is_active), [profiles, currentUserId]);
  const unreadByUser = useMemo(() => { const counts = new Map<string, number>(); for (const m of messages) if (m.recipient_id === currentUserId && m.read_at === null) counts.set(m.sender_id, (counts.get(m.sender_id) ?? 0) + 1); return counts; }, [messages, currentUserId]);
  const latestByUser = useMemo(() => { const latest = new Map<string, Message>(); for (const m of messages) { const other = m.sender_id === currentUserId ? m.recipient_id : m.sender_id; const old = latest.get(other); if (!old || new Date(m.created_at).getTime() > new Date(old.created_at).getTime()) latest.set(other, m); } return latest; }, [messages, currentUserId]);
  const filteredRecipients = useMemo(() => { const q = search.trim().toLowerCase(); const filtered = q ? recipients.filter((p) => [p.full_name, p.role, p.designation ?? "", p.username ?? ""].join(" ").toLowerCase().includes(q)) : recipients; return [...filtered].sort((a,b) => { const unread = (unreadByUser.get(b.user_id) ?? 0) - (unreadByUser.get(a.user_id) ?? 0); if (unread) return unread; return (latestByUser.get(b.user_id) ? new Date(latestByUser.get(b.user_id)!.created_at).getTime() : 0) - (latestByUser.get(a.user_id) ? new Date(latestByUser.get(a.user_id)!.created_at).getTime() : 0); }); }, [recipients, search, unreadByUser, latestByUser]);
  const selectedProfile = recipients.find((p) => p.user_id === selectedUserId) ?? null;
  const threadMessages = useMemo(() => selectedUserId ? messages.filter((m) => (m.sender_id === currentUserId && m.recipient_id === selectedUserId) || (m.sender_id === selectedUserId && m.recipient_id === currentUserId)) : [], [messages, currentUserId, selectedUserId]);
  useEffect(() => { if (selectedUserId && (unreadByUser.get(selectedUserId) ?? 0) > 0) startReadTransition(() => { void markMessagesRead(selectedUserId); }); }, [selectedUserId, unreadByUser]);
  async function handleSend(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!selectedProfile || !body.trim() || submitting) return; setSubmitting(true); const r = await sendMessage(selectedProfile.user_id, body); setSubmitting(false); if (r.error) { toast(r.error,"danger"); return; } setBody(""); toast("Message sent","success"); router.refresh(); }
  async function handleBroadcast(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!broadcastBody.trim() || broadcasting) return; setBroadcasting(true); const r = await broadcastOwnerMessage(broadcastBody); setBroadcasting(false); if (r.error) { toast(r.error,"danger"); return; } setBroadcastBody(""); setBroadcastOpen(false); toast(`Message sent to ${r.sent} active staff members`,"success"); router.refresh(); }
  return <div className="flex h-[calc(100dvh-4rem)] min-h-0 flex-col p-3 sm:p-5">
    <div className="mb-3 flex shrink-0 items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-neutral-900">Messages</h1><p className="text-xs text-neutral-500">{roleLabel} · message any active staff member</p></div><div className="flex gap-2">{roleLabel === "Owner" && <Button type="button" size="sm" onClick={() => setBroadcastOpen(true)}>Message everyone</Button>}{selectedProfile && <Button type="button" size="sm" variant="ghost" onClick={() => setSelectedUserId(null)} className="md:hidden">Back</Button>}</div></div>
    {roleLabel === "Owner" && broadcastOpen && <div className="mb-3 shrink-0 rounded-2xl border border-primary-200 bg-primary-50 p-4"><h2 className="text-sm font-semibold text-neutral-900">Message everyone</h2><p className="mt-1 text-xs text-neutral-500">One direct message will be sent to every active staff account except you.</p><form onSubmit={handleBroadcast} className="mt-3 space-y-3"><Textarea label="Announcement" value={broadcastBody} onChange={(e) => setBroadcastBody(e.target.value)} placeholder="Write your message…" rows={3} disabled={broadcasting} required /><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setBroadcastOpen(false)} disabled={broadcasting}>Cancel</Button><Button type="submit" loading={broadcasting} disabled={!broadcastBody.trim()}>Send to everyone</Button></div></form></div>}
    <div className="grid min-h-0 flex-1 grid-cols-1 gap-3 overflow-hidden md:grid-cols-[300px_minmax(0,1fr)]">
      <aside className={`${selectedProfile ? "hidden md:flex" : "flex"} min-h-0 flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white`}><div className="shrink-0 border-b border-neutral-200 p-3"><label htmlFor="message-search" className="sr-only">Search people</label><input id="message-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search people…" autoComplete="off" className="h-10 w-full rounded-xl border border-neutral-300 px-3 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500" /></div><div className="min-h-0 flex-1 overflow-y-auto">{filteredRecipients.length === 0 ? <div className="p-4 text-sm text-neutral-500">No active staff found.</div> : <ul className="divide-y divide-neutral-100">{filteredRecipients.map((p) => { const unread = unreadByUser.get(p.user_id) ?? 0; const latest = latestByUser.get(p.user_id); return <li key={p.user_id}><button type="button" onClick={() => setSelectedUserId(p.user_id)} className={`flex min-h-[68px] w-full items-center gap-3 px-3 py-3 text-left hover:bg-neutral-50 ${selectedUserId === p.user_id ? "bg-primary-50" : ""}`}><Avatar name={p.full_name} size="md" /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className={`truncate text-sm ${unread ? "font-bold text-neutral-950" : "font-medium text-neutral-900"}`}><Bdi>{p.full_name}</Bdi></span>{unread > 0 && <span className="rounded-full bg-primary-600 px-2 py-0.5 text-[10px] font-semibold text-white">{unread}</span>}</span><span className="block truncate text-xs text-neutral-500">{p.role.replace("_", " ")}{latest ? ` · ${latest.body}` : ""}</span></span></button></li>; })}</ul>}</div></aside>
      <section className={`${selectedProfile ? "flex" : "hidden md:flex"} min-h-0 flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white`}>{selectedProfile ? <><header className="flex min-h-[60px] shrink-0 items-center gap-3 border-b border-neutral-200 px-3"><Button type="button" size="sm" variant="ghost" onClick={() => setSelectedUserId(null)} className="md:hidden">‹</Button><Avatar name={selectedProfile.full_name} size="sm" /><div className="min-w-0"><div className="truncate text-sm font-semibold text-neutral-900"><Bdi>{selectedProfile.full_name}</Bdi></div><div className="truncate text-xs capitalize text-neutral-500">{selectedProfile.designation ?? selectedProfile.role.replace("_", " ")}</div></div></header><div className="min-h-0 flex-1 overflow-y-auto px-3 py-4">{threadMessages.length === 0 ? <EmptyState title="No messages yet" description={`Start a conversation with ${selectedProfile.full_name}.`} /> : <ChatThread messages={threadMessages} currentUserId={currentUserId} />}</div><form onSubmit={handleSend} className="shrink-0 border-t border-neutral-200 bg-white p-2"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><Textarea label="Message" value={body} onChange={(e) => setBody(e.target.value)} placeholder="Type a message…" rows={2} className="min-h-[44px] max-h-32 resize-none text-base sm:text-sm" disabled={submitting} required /></div><Button type="submit" size="md" loading={submitting} disabled={!body.trim()}>Send</Button></div></form></> : <div className="flex flex-1 items-center justify-center p-6 text-center"><div><h2 className="text-base font-semibold text-neutral-900">Choose someone to message</h2><p className="mt-1 text-sm text-neutral-500">Every active School OS staff account is available here.</p></div></div>}</section>
    </div>
  </div>;
}
export function MessagesClient(props: MessagesClientProps) { return <ToastProvider><MessagesInner {...props} /></ToastProvider>; }
