import { notFound } from "next/navigation";
import { requireAnyRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { StudentRiskProfile, type StudentSubjectRisk, type StudentTestRow } from "@/components/examination/student-risk-profile";

export default async function StudentRiskPage({params}:{params:{id:string}}){
 await requireAnyRole(["owner","academic_coordinator"]); const supabase=createClient();
 const [{data:student},{data:classes},{data:schedules},{data:subjects},{data:results},{data:topics},{data:chapters}]=await Promise.all([
  supabase.from('students').select('id,name,roll_no,class_id').eq('id',params.id).maybeSingle(),supabase.from('classes').select('id,name'),supabase.from('schedule_items').select('id,title,subject_id,topic_id,scheduled_date,status'),supabase.from('subjects').select('id,name'),supabase.from('test_results').select('schedule_item_id,marks_obtained,total_marks,is_absent,is_pass').eq('student_id',params.id),supabase.from('topics').select('id,name,chapter_id'),supabase.from('chapters').select('id,subject_id')
 ]);
 if(!student)notFound();
 const className=(classes??[]).find(c=>c.id===student.class_id)?.name??'Unknown class'; const subjectMap=new Map((subjects??[]).map(s=>[s.id,s.name])); const scheduleMap=new Map((schedules??[]).map(s=>[s.id,s])); const chapterMap=new Map((chapters??[]).map(c=>[c.id,c.subject_id]));
 const subjectRows=new Map<string,{sum:number;total:number;tests:number;failed:number;last:number|null;prev:number|null}>(); const weakTopics=new Map<string,number>(); const tests:StudentTestRow[]=[];
 for(const r of results??[]){const s=scheduleMap.get(r.schedule_item_id);if(!s)continue;const name=subjectMap.get(s.subject_id)??'Unknown';const row=subjectRows.get(s.subject_id)??{sum:0,total:0,tests:0,failed:0,last:null,prev:null};row.tests++;if(!r.is_absent&&r.marks_obtained!=null){row.sum+=Number(r.marks_obtained);row.total+=Number(r.total_marks);if(row.last==null)row.last=Number(r.marks_obtained)/Number(r.total_marks)*100;else if(row.prev==null)row.prev=Number(r.marks_obtained)/Number(r.total_marks)*100;}if(r.is_pass===false)row.failed++;subjectRows.set(s.subject_id,row);tests.push({date:s.scheduled_date,title:s.title,subject:name,marks:r.is_absent?'—':`${r.marks_obtained??'—'}/${r.total_marks}`,status:r.is_absent?'Absent':r.is_pass===false?'Fail':'Pass'});if(s.topic_id&&r.is_pass===false){const topicName=(topics??[]).find(t=>t.id===s.topic_id)?.name;if(topicName)weakTopics.set(topicName,(weakTopics.get(topicName)??0)+1)}}
 const subjectsRisk:StudentSubjectRisk[]=Array.from(subjectRows.entries()).map(([id,r])=>({subject:subjectMap.get(id)??'Unknown',tests:r.tests,average:r.total?Math.round(r.sum/r.total*100):0,failed:r.failed,trend:r.last!=null&&r.prev!=null?Math.round(r.last-r.prev):null}));const graded=subjectsRisk.reduce((a,s)=>a+s.tests,0);const totalFails=subjectsRisk.reduce((a,s)=>a+s.failed,0);const average=subjectsRisk.length?Math.round(subjectsRisk.reduce((a,s)=>a+s.average,0)/subjectsRisk.length):0;const riskScore=Math.min(100,Math.round(totalFails/Math.max(graded,1)*65+Math.max(0,60-average)*.8));tests.sort((a,b)=>b.date.localeCompare(a.date));return <StudentRiskProfile name={student.name} rollNo={student.roll_no} className={className} riskScore={riskScore} average={average} failed={totalFails} subjects={subjectsRisk} tests={tests.slice(0,12)} weakTopics={Array.from(weakTopics.entries()).sort((a,b)=>b[1]-a[1]).map(([name])=>name).slice(0,8)}/>;
}
