import Link from "next/link";
import type { Class, Subject } from "@/types/examination";
import { requireAnyRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { classOrderIndex } from "@/components/examination/constants";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { GenerateSetForm } from "./generate-set-form";

type ExamSetStatus = "planned" | "active" | "awaiting_completion" | "completed" | "cancelled";

interface ExamSetRow {
  id: string;
  class_id: string;
  set_number: number;
  status: ExamSetStatus;
  assessment_scope: string;
  started_on: string | null;
  completed_on: string | null;
}

interface ExamSetSubjectRow {
  id: string;
  exam_set_id: string;
  subject_id: string;
  sequence: number;
  scheduled_date: string | null;
  schedule_item_id: string | null;
}

interface ScheduleItemStatusRow {
  id: string;
  status: string;
}

const STATUS_VARIANT: Record<ExamSetStatus, "success" | "warning" | "danger" | "neutral" | "info"> = {
  planned: "neutral",
  active: "info",
  awaiting_completion: "warning",
  completed: "success",
  cancelled: "neutral"
};

const IN_PROGRESS_STATUSES: ExamSetStatus[] = ["planned", "active", "awaiting_completion"];

function formatScope(scope: string): string {
  return scope.replace(/_/g, " ");
}

export default async function CoordinatorExamSetsPage() {
  const profile = await requireAnyRole(["owner", "academic_coordinator"]);
  const canManage = profile.role === "academic_coordinator";
  const supabase = createClient();

  const [classesRes, subjectsRes, examSetsRes, examSetSubjectsRes, scheduleItemsRes] =
    await Promise.all([
      supabase.from("classes").select("*"),
      supabase.from("subjects").select("*"),
      supabase
        .from("exam_sets")
        .select("id,class_id,set_number,status,assessment_scope,started_on,completed_on")
        .order("class_id", { ascending: true })
        .order("set_number", { ascending: false }),
      supabase
        .from("exam_set_subjects")
        .select("id,exam_set_id,subject_id,sequence,scheduled_date,schedule_item_id")
        .order("sequence", { ascending: true }),
      supabase.from("schedule_items").select("id,status")
    ]);

  const classes = ((classesRes.data as Class[] | null) ?? [])
    .slice()
    .sort((a, b) => classOrderIndex(a.name) - classOrderIndex(b.name));
  const subjects = (subjectsRes.data as Subject[] | null) ?? [];
  const examSets = (examSetsRes.data as ExamSetRow[] | null) ?? [];
  const examSetSubjects = (examSetSubjectsRes.data as ExamSetSubjectRow[] | null) ?? [];
  const scheduleItems = (scheduleItemsRes.data as ScheduleItemStatusRow[] | null) ?? [];

  const subjectById = new Map(subjects.map((s) => [s.id, s]));
  const scheduleItemStatusById = new Map(scheduleItems.map((si) => [si.id, si.status]));

  const activeSubjectsByClass: Record<string, Subject[]> = {};
  for (const subject of subjects) {
    if (!subject.is_active) continue;
    (activeSubjectsByClass[subject.class_id] ??= []).push(subject);
  }

  const examSetsByClass: Record<string, ExamSetRow[]> = {};
  for (const set of examSets) {
    (examSetsByClass[set.class_id] ??= []).push(set);
  }

  const subjectRowsByExamSet: Record<string, ExamSetSubjectRow[]> = {};
  for (const row of examSetSubjects) {
    (subjectRowsByExamSet[row.exam_set_id] ??= []).push(row);
  }

  const classesWithSubjects = classes.filter(
    (c) => (activeSubjectsByClass[c.id] ?? []).length > 0
  );

  if (classesWithSubjects.length === 0) {
    return (
      <main className="flex flex-col gap-5 p-4 sm:p-6">
        <div>
          <h1 className="text-xl font-semibold text-neutral-900">Exam sets</h1>
          <p className="mt-1 text-sm text-neutral-500">
            Continuous exam-cycle progress per class, generated by the exam-scheduling engine.
          </p>
        </div>
        <Card>
          <CardContent>
            <EmptyState
              title="No classes with active subjects yet."
              description="Once a class has active subjects, its exam-cycle progress will appear here."
            />
          </CardContent>
        </Card>
      </main>
    );
  }

  return (
    <main className="flex flex-col gap-5 p-4 sm:p-6">
      <div>
        <h1 className="text-xl font-semibold text-neutral-900">Exam sets</h1>
        <p className="mt-1 text-sm text-neutral-500">
          Continuous exam-cycle progress per class. Each set schedules one exam per active
          subject; a new set can only be generated once the current one is completed or
          cancelled.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {classesWithSubjects.map((klass) => {
          const activeSubjects = activeSubjectsByClass[klass.id] ?? [];
          const classSets = examSetsByClass[klass.id] ?? [];
          const latestSet = classSets[0] ?? null;
          const hasSetInProgress = classSets.some((s) =>
            IN_PROGRESS_STATUSES.includes(s.status)
          );

          return (
            <Card key={klass.id}>
              <CardHeader>
                <CardTitle>{klass.name}</CardTitle>
                <p className="mt-1 text-xs text-neutral-500">
                  {activeSubjects.length} active subject{activeSubjects.length === 1 ? "" : "s"}
                </p>
              </CardHeader>
              <CardContent className="flex flex-col gap-3">
                {!latestSet ? (
                  <p className="text-sm text-neutral-500">No exam set started yet.</p>
                ) : (
                  <div className="rounded-xl border border-neutral-200 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <Link
                        href={`/coordinator/exam-sets/${latestSet.id}`}
                        className="text-sm font-semibold text-neutral-900 hover:underline"
                      >
                        Set #{latestSet.set_number} · View report
                      </Link>
                      <Badge variant={STATUS_VARIANT[latestSet.status]}>
                        {latestSet.status.replace(/_/g, " ")}
                      </Badge>
                    </div>
                    <p className="mt-1 text-xs text-neutral-500">
                      {formatScope(latestSet.assessment_scope)}
                      {latestSet.started_on ? ` · started ${latestSet.started_on}` : ""}
                      {latestSet.completed_on ? ` · completed ${latestSet.completed_on}` : ""}
                    </p>

                    {(() => {
                      const rows = subjectRowsByExamSet[latestSet.id] ?? [];
                      if (rows.length === 0) return null;
                      return (
                        <ul className="mt-3 flex flex-col gap-1.5 border-t border-neutral-100 pt-2">
                          {rows.map((row) => {
                            const subject = subjectById.get(row.subject_id);
                            const itemStatus = row.schedule_item_id
                              ? scheduleItemStatusById.get(row.schedule_item_id)
                              : null;
                            return (
                              <li
                                key={row.id}
                                className="flex flex-wrap items-center justify-between gap-2 text-xs"
                              >
                                <span className="text-neutral-700">
                                  {subject?.name ?? "Unknown subject"}
                                  {row.scheduled_date ? ` · ${row.scheduled_date}` : ""}
                                </span>
                                {itemStatus && <Badge variant="neutral">{itemStatus}</Badge>}
                              </li>
                            );
                          })}
                        </ul>
                      );
                    })()}
                  </div>
                )}

                {canManage && !hasSetInProgress && <GenerateSetForm classId={klass.id} />}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </main>
  );
}
