import type { Class, Student, Subject } from "@/types/examination";
import type { Profile } from "@/types/database";
import { createClient } from "@/lib/supabase/server";
import type { DangerRow, HealthMetric, ReadinessRow, StudentRiskRow, TeacherComplianceRow } from "@/components/examination/academic-intelligence";
interface ScheduleRow { id:string; class_id:string; subject_id:string; topic_id:string|null; teacher_id:string|null; status:string; scheduled_date:string; title:string; }
interface PaperRow { id:string; schedule_item_id:string; teacher_id:string; status:string; print_status:string|null; review_notes:string|null; }
interface ResultRow { schedule_item_id:string; student_id:string; marks_obtained:number|null; total_marks:number; is_absent:boolean; is_pass:boolean|null; }
interface SubmissionRow { schedule_item_id:string; status:string; }
const pct=(n:number,d:number)=>d>0?Math.round(n/d*100):100;
export interface AcademicIntelligenceData { readiness:ReadinessRow[]; dangers:DangerRow[]; studentRisks:StudentRiskRow[]; teachers:TeacherComplianceRow[]; healthMetrics:HealthMetric[]; healthScore:number; }
export async function getAcademicIntelligenceData():Promise<AcademicIntelligenceData>{
 const supabase=createClient(); const today=new Date(); const todayIso=today.toISOString().slice(0,10); const end=new Date(today); end.setDate(end.getDate()+7); const endIso=end.toISOString().slice(0,10);
 const [schedulesRes,papersRes,resultsRes,submissionsRes,classesRes,subjectsRes,studentsRes,teachersRes]=await Promise.all([
  supabase.from("schedule_items").select("id,class_id,subject_id,topic_id,teacher_id,status,scheduled_date,title"),
  supabase.from("exam_papers").select("id,schedule_item_id,teacher_id,status,print_status,review_notes"),
  supabase.from("test_results").select("schedule_item_id,student_id,marks_obtained,total_marks,is_absent,is_pass"),
  supabase.from("result_submissions").select("schedule_item_id,status"),
  supabase.from("classes").select("*"), supabase.from("subjects").select("*"), supabase.from("students").select("*").eq("is_active",true),
  supabase.from("profiles").select("user_id,id,full_name,role,is_active").eq("role","teacher").eq("is_active",true)
 ]);
 const schedules=(schedulesRes.data as ScheduleRow[]|null)??[]; const papers=(papersRes.data as PaperRow[]|null)??[]; const results=(resultsRes.data as ResultRow[]|null)??[]; const submissions=(submissionsRes.data as SubmissionRow[]|null)??[]; const classes=(classesRes.data as Class[]|null)??[]; const subjects=(subjectsRes.data as Subject[]|null)??[]; const students=(studentsRes.data as Student[]|null)??[]; const teachers=(teachersRes.data as Profile[]|null)??[];
 const classById=new Map(classes.map(r=>[r.id,r])); const subjectById=new Map(subjects.map(r=>[r.id,r])); const teacherById=new Map(teachers.map(r=>[r.user_id,r])); const paperBySchedule=new Map(papers.map(r=>[r.schedule_item_id,r])); const submissionBySchedule=new Map(submissions.map(r=>[r.schedule_item_id,r])); const scheduleById=new Map(schedules.map(r=>[r.id,r]));
 const resultsBySchedule=new Map<string,ResultRow[]>(); const resultsByStudent=new Map<string,ResultRow[]>(); for(const r of results){let a=resultsBySchedule.get(r.schedule_item_id);if(!a){a=[];resultsBySchedule.set(r.schedule_item_id,a)}a.push(r);let b=resultsByStudent.get(r.student_id);if(!b){b=[];resultsByStudent.set(r.student_id,b)}b.push(r);}
 const readiness=schedules.filter(s=>s.status!=="cancelled"&&s.scheduled_date>=todayIso&&s.scheduled_date<=endIso).sort((a,b)=>a.scheduled_date.localeCompare(b.scheduled_date)).map(s=>{const p=paperBySchedule.get(s.id);const rows=resultsBySchedule.get(s.id)??[];const expected=students.filter(st=>st.class_id===s.class_id).length;const checks=[!!p,!!p&&p.status==="approved",!!p&&p.print_status==="printed",s.status==="completed",expected>0&&rows.length>=expected,submissionBySchedule.get(s.id)?.status==="finalized"];return{id:s.id,title:s.title,date:s.scheduled_date,className:classById.get(s.class_id)?.name??"Unknown class",subjectName:subjectById.get(s.subject_id)?.name??"Unknown subject",teacherName:teacherById.get(s.teacher_id??"")?.full_name??"Unassigned",paper:!!checks[0],approved:!!checks[1],printed:!!checks[2],conducted:!!checks[3],resultsComplete:!!checks[4],resultsFinalized:!!checks[5],score:Math.round(checks.filter(Boolean).length/checks.length*100)};});
 const dangers:DangerRow[]=[];for(const r of readiness){const days=Math.round((new Date(`${r.date}T00:00:00`).getTime()-new Date(`${todayIso}T00:00:00`).getTime())/86400000);const p=paperBySchedule.get(r.id);if(!r.paper&&days<=2)dangers.push({severity:days<=1?"urgent":"high",label:"Paper missing",detail:`${r.title} is due ${r.date}.`,href:"/coordinator/papers"});if(r.approved&&!r.printed&&days<=1)dangers.push({severity:"critical",label:"Approved paper not printed",detail:`${r.title} is scheduled ${r.date}.`,href:"/clerk/papers"});if(p?.status==="draft"&&p.review_notes)dangers.push({severity:"high",label:"Paper needs correction",detail:`${r.title} has review feedback awaiting a revision.`,href:"/coordinator/papers"});}
 const studentRisks:StudentRiskRow[]=[];for(const st of students){const graded=(resultsByStudent.get(st.id)??[]).filter(r=>r.is_pass!==null&&!r.is_absent);if(graded.length<2)continue;const dated=graded.slice().sort((a,b)=>(scheduleById.get(b.schedule_item_id)?.scheduled_date??"").localeCompare(scheduleById.get(a.schedule_item_id)?.scheduled_date??""));const failed=graded.filter(r=>r.is_pass===false).length;const average=pct(graded.reduce((s,r)=>s+(Number(r.marks_obtained)||0),0),graded.reduce((s,r)=>s+Number(r.total_marks),0));const consecutive=dated.slice(0,3).length===3&&dated.slice(0,3).every(r=>r.is_pass===false);const subjectIds=new Set(graded.map(r=>scheduleById.get(r.schedule_item_id)?.subject_id).filter((v):v is string=>Boolean(v)));const weakSubjects=Array.from(subjectIds).map(id=>subjectById.get(id)?.name??"Unknown").slice(0,3);const score=Math.min(100,Math.round(failed/Math.max(graded.length,1)*65+Math.max(0,60-average)*.8+(consecutive?25:0)));if(score>=35)studentRisks.push({id:st.id,name:st.name,rollNo:st.roll_no,className:classById.get(st.class_id)?.name??"Unknown class",score,failed,average,weakSubjects});}studentRisks.sort((a,b)=>b.score-a.score);
 const teacherCompliance:TeacherComplianceRow[]=teachers.map(t=>{const ts=schedules.filter(s=>s.teacher_id===t.user_id&&s.status!=="cancelled"&&s.scheduled_date<=endIso);const scheduled=ts.length;const papersCount=ts.filter(s=>{const st=paperBySchedule.get(s.id)?.status;return !!st&&!['not_started','draft'].includes(st);}).length;const completed=ts.filter(s=>s.status==='completed').length;const completedResults=ts.filter(s=>{const expected=students.filter(st=>st.class_id===s.class_id).length;return expected>0&&(resultsBySchedule.get(s.id)?.length??0)>=expected;}).length;const paperScore=pct(papersCount,scheduled),testScore=pct(completed,scheduled),resultScore=pct(completedResults,completed);return{id:t.user_id,name:t.full_name,scheduled,papers:papersCount,completed,results:completedResults,score:Math.round(paperScore*.35+testScore*.3+resultScore*.35)}}).sort((a,b)=>a.score-b.score);
 const completedSchedules=schedules.filter(s=>s.status==='completed');const upcomingReadiness=readiness.length?Math.round(readiness.reduce((sum,r)=>sum+r.score,0)/readiness.length):100;const teacherScore=teacherCompliance.length?Math.round(teacherCompliance.reduce((sum,r)=>sum+r.score,0)/teacherCompliance.length):100;const resultCompletion=completedSchedules.length?Math.round(completedSchedules.filter(s=>{const expected=students.filter(st=>st.class_id===s.class_id).length;return expected>0&&(resultsBySchedule.get(s.id)?.length??0)>=expected;}).length/completedSchedules.length*100):100;const graded=results.filter(r=>r.is_pass!==null&&!r.is_absent);const performanceScore=graded.length?Math.round(graded.filter(r=>r.is_pass).length/graded.length*100):100;const topicsCovered=new Set(schedules.filter(s=>s.status==='completed'&&s.topic_id).map(s=>s.topic_id as string));const topicCountRes=await supabase.from("topics").select("id",{count:"exact",head:true});const syllabusScore=pct(topicsCovered.size,topicCountRes.count??0);
 const healthMetrics:HealthMetric[]=[{label:"Exam readiness",score:upcomingReadiness,detail:`${readiness.length} exam(s) in the next 7 days`},{label:"Teacher compliance",score:teacherScore,detail:"Paper, test, and result completion"},{label:"Result completion",score:resultCompletion,detail:`${completedSchedules.length} completed test(s)`},{label:"Student performance",score:performanceScore,detail:graded.length?`${graded.length} graded attempts`:"No graded data yet"},{label:"Syllabus progress",score:syllabusScore,detail:`${topicsCovered.size} of ${topicCountRes.count??0} topics covered`}];
 return{readiness,dangers:dangers.slice(0,10),studentRisks:studentRisks.slice(0,10),teachers:teacherCompliance,healthMetrics,healthScore:Math.round(healthMetrics.reduce((sum,m)=>sum+m.score,0)/healthMetrics.length)};
}
